//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfFileTypePlugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new SingleAssemblyResourceManager("PdfFileTypePlugin.Localization.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        internal static string AllPages {
            get {
                return ResourceManager.GetString("AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available!.
        /// </summary>
        internal static string AnUpdateIsAvailable {
            get {
                return ResourceManager.GetString("AnUpdateIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as is.
        /// </summary>
        internal static string AsIs {
            get {
                return ResourceManager.GetString("AsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend mode.
        /// </summary>
        internal static string BlendMode {
            get {
                return ResourceManager.GetString("BlendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend onto.
        /// </summary>
        internal static string BlendOnto {
            get {
                return ResourceManager.GetString("BlendOnto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled upon your request..
        /// </summary>
        internal static string CanceledUponYourRequest {
            get {
                return ResourceManager.GetString("CanceledUponYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        internal static string ContentAlignmentBottomCenter {
            get {
                return ResourceManager.GetString("ContentAlignmentBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string ContentAlignmentBottomLeft {
            get {
                return ResourceManager.GetString("ContentAlignmentBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string ContentAlignmentBottomRight {
            get {
                return ResourceManager.GetString("ContentAlignmentBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        internal static string ContentAlignmentMiddleCenter {
            get {
                return ResourceManager.GetString("ContentAlignmentMiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        internal static string ContentAlignmentMiddleLeft {
            get {
                return ResourceManager.GetString("ContentAlignmentMiddleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        internal static string ContentAlignmentMiddleRight {
            get {
                return ResourceManager.GetString("ContentAlignmentMiddleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        internal static string ContentAlignmentTopCenter {
            get {
                return ResourceManager.GetString("ContentAlignmentTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string ContentAlignmentTopLeft {
            get {
                return ResourceManager.GetString("ContentAlignmentTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string ContentAlignmentTopRight {
            get {
                return ResourceManager.GetString("ContentAlignmentTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Range.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` field is empty or invalid..
        /// </summary>
        internal static string CustomFieldError {
            get {
                return ResourceManager.GetString("CustomFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 1-5, 8, 11-13.
        /// </summary>
        internal static string CustomPagesPlaceHolderText {
            get {
                return ResourceManager.GetString("CustomPagesPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Layer and Document Properties.
        /// </summary>
        internal static string EmbedLayerAndDocumentProperties {
            get {
                return ResourceManager.GetString("EmbedLayerAndDocumentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped.
        /// </summary>
        internal static string ExportModeCropped {
            get {
                return ResourceManager.GetString("ExportModeCropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative.
        /// </summary>
        internal static string ExportModeCumulative {
            get {
                return ResourceManager.GetString("ExportModeCumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flattened.
        /// </summary>
        internal static string ExportModeFlattened {
            get {
                return ResourceManager.GetString("ExportModeFlattened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ExportModeNormal {
            get {
                return ResourceManager.GetString("ExportModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string ForumLink {
            get {
                return ResourceManager.GetString("ForumLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible (except first layer).
        /// </summary>
        internal static string Invisible {
            get {
                return ResourceManager.GetString("Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additive.
        /// </summary>
        internal static string LayerBlendModeAdditive {
            get {
                return ResourceManager.GetString("LayerBlendModeAdditive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Burn.
        /// </summary>
        internal static string LayerBlendModeColorBurn {
            get {
                return ResourceManager.GetString("LayerBlendModeColorBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Dodge.
        /// </summary>
        internal static string LayerBlendModeColorDodge {
            get {
                return ResourceManager.GetString("LayerBlendModeColorDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darken.
        /// </summary>
        internal static string LayerBlendModeDarken {
            get {
                return ResourceManager.GetString("LayerBlendModeDarken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        internal static string LayerBlendModeDifference {
            get {
                return ResourceManager.GetString("LayerBlendModeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        internal static string LayerBlendModeGlow {
            get {
                return ResourceManager.GetString("LayerBlendModeGlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighten.
        /// </summary>
        internal static string LayerBlendModeLighten {
            get {
                return ResourceManager.GetString("LayerBlendModeLighten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        internal static string LayerBlendModeMultiply {
            get {
                return ResourceManager.GetString("LayerBlendModeMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negation.
        /// </summary>
        internal static string LayerBlendModeNegation {
            get {
                return ResourceManager.GetString("LayerBlendModeNegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string LayerBlendModeNormal {
            get {
                return ResourceManager.GetString("LayerBlendModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string LayerBlendModeOverlay {
            get {
                return ResourceManager.GetString("LayerBlendModeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflect.
        /// </summary>
        internal static string LayerBlendModeReflect {
            get {
                return ResourceManager.GetString("LayerBlendModeReflect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string LayerBlendModeScreen {
            get {
                return ResourceManager.GetString("LayerBlendModeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xor.
        /// </summary>
        internal static string LayerBlendModeXor {
            get {
                return ResourceManager.GetString("LayerBlendModeXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain aspect ratio.
        /// </summary>
        internal static string MaintainAspectRatio {
            get {
                return ResourceManager.GetString("MaintainAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page count.
        /// </summary>
        internal static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page #{0}.
        /// </summary>
        internal static string PageNumberFormat {
            get {
                return ResourceManager.GetString("PageNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF standard.
        /// </summary>
        internal static string PDFStandard {
            get {
                return ResourceManager.GetString("PDFStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PdfStandardNone {
            get {
                return ResourceManager.GetString("PdfStandardNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a color.
        /// </summary>
        internal static string PickAColor {
            get {
                return ResourceManager.GetString("PickAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password..
        /// </summary>
        internal static string PleaseEnterThePassword {
            get {
                return ResourceManager.GetString("PleaseEnterThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin version: {0}.
        /// </summary>
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ? Preview generation is not supported by this plugin.
        ///? DO NOT use this plugin to edit random PDF files.
        ///? DO NOT overwrite the original PDF file or make sure you&apos;ve a backup.
        ///? PDF/A-1 prohibits the use of transparency within a conforming document..
        /// </summary>
        internal static string PreviewText {
            get {
                return ResourceManager.GetString("PreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! NOTES ABOUT PDF FILE TYPE PLUGIN !!!.
        /// </summary>
        internal static string PreviewTextHeader {
            get {
                return ResourceManager.GetString("PreviewTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        internal static string Px {
            get {
                return ResourceManager.GetString("Px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        internal static string RenderingFlagsGrayscale {
            get {
                return ResourceManager.GetString("RenderingFlagsGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale output..
        /// </summary>
        internal static string RenderingFlagsGrayscaleDesc {
            get {
                return ResourceManager.GetString("RenderingFlagsGrayscaleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCD Text.
        /// </summary>
        internal static string RenderingFlagsLcdText {
            get {
                return ResourceManager.GetString("RenderingFlagsLcdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set if using text rendering optimized for LCD display..
        /// </summary>
        internal static string RenderingFlagsLcdTextDesc {
            get {
                return ResourceManager.GetString("RenderingFlagsLcdTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Smooth Image.
        /// </summary>
        internal static string RenderingFlagsNoSmoothImage {
            get {
                return ResourceManager.GetString("RenderingFlagsNoSmoothImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to disable anti-aliasing on images..
        /// </summary>
        internal static string RenderingFlagsNoSmoothImageDesc {
            get {
                return ResourceManager.GetString("RenderingFlagsNoSmoothImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Smooth Path.
        /// </summary>
        internal static string RenderingFlagsNoSmoothPath {
            get {
                return ResourceManager.GetString("RenderingFlagsNoSmoothPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to disable anti-aliasing on paths..
        /// </summary>
        internal static string RenderingFlagsNoSmoothPathDesc {
            get {
                return ResourceManager.GetString("RenderingFlagsNoSmoothPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Smooth Text.
        /// </summary>
        internal static string RenderingFlagsNoSmoothText {
            get {
                return ResourceManager.GetString("RenderingFlagsNoSmoothText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to disable anti-aliasing on text..
        /// </summary>
        internal static string RenderingFlagsNoSmoothTextDesc {
            get {
                return ResourceManager.GetString("RenderingFlagsNoSmoothTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render options.
        /// </summary>
        internal static string RenderOptions {
            get {
                return ResourceManager.GetString("RenderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore properties (if available).
        /// </summary>
        internal static string RestoreLayerProperties {
            get {
                return ResourceManager.GetString("RestoreLayerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip duplicate layers.
        /// </summary>
        internal static string SkipDuplicateLayers {
            get {
                return ResourceManager.GetString("SkipDuplicateLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip invisible layers.
        /// </summary>
        internal static string SkipInvisibleLayers {
            get {
                return ResourceManager.GetString("SkipInvisibleLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varies.
        /// </summary>
        internal static string Varies {
            get {
                return ResourceManager.GetString("Varies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
